version: '3.8'

services:
  # Frontend development service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: pedro-frontend-dev
    working_dir: /app/frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://backend:3001
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - pedro-network

  # Backend development service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: pedro-backend-dev
    working_dir: /app/backend
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - pedro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Redis cache service
  redis:
    image: redis:7-alpine
    container_name: pedro-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - pedro-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  pedro-network:
    driver: bridge

volumes:
  redis-data:
    driver: local