[build]
  base = "."
  command = "./build-all.sh"
  functions = "frontend/netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Subdomain redirects - These handle subdomain routing
[[redirects]]
  from = "https://tmj.gregpedromd.com/*"
  to = "/tmj/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://implants.gregpedromd.com/*"
  to = "/implants/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://robotic.gregpedromd.com/*"
  to = "/robotic/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://medspa.gregpedromd.com/*"
  to = "/medspa/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://aboutface.gregpedromd.com/*"
  to = "/aboutface/:splat"
  status = 200
  force = true

# Path-based routing for subdomains (when accessed via main domain)
[[redirects]]
  from = "/tmj/*"
  to = "/tmj/index.html"
  status = 200

[[redirects]]
  from = "/implants/*"
  to = "/implants/index.html"
  status = 200

[[redirects]]
  from = "/robotic/*"
  to = "/robotic/index.html"
  status = 200

[[redirects]]
  from = "/medspa/*"
  to = "/medspa/index.html"
  status = 200

[[redirects]]
  from = "/aboutface/*"
  to = "/aboutface/index.html"
  status = 200

# Main domain fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
