name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

env:
  NODE_VERSION: '18.x'

jobs:
  # CodeQL Analysis
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'typescript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  # Dependency vulnerability scanning
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm audit for frontend
        working-directory: ./frontend
        run: |
          npm audit --json > frontend-audit.json || true
          if [ -s frontend-audit.json ]; then
            echo "::warning::Frontend vulnerabilities found"
            cat frontend-audit.json | jq '.vulnerabilities | to_entries[] | select(.value.severity == "high" or .value.severity == "critical") | {name: .key, severity: .value.severity, title: .value.title}'
          fi

      - name: Run npm audit for backend
        working-directory: ./backend
        run: |
          npm audit --json > backend-audit.json || true
          if [ -s backend-audit.json ]; then
            echo "::warning::Backend vulnerabilities found"
            cat backend-audit.json | jq '.vulnerabilities | to_entries[] | select(.value.severity == "high" or .value.severity == "critical") | {name: .key, severity: .value.severity, title: .value.title}'
          fi

      - name: Upload audit reports
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: |
            frontend/frontend-audit.json
            backend/backend-audit.json
          retention-days: 7

  # Secret scanning
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # OWASP Dependency Check
  owasp-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'pedro-dental'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
            --enableExperimental
            --scan frontend/package-lock.json
            --scan backend/package-lock.json

      - name: Upload OWASP results
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: reports/dependency-check-report.html
          retention-days: 7

  # Security headers check
  security-headers:
    name: Security Headers Check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check security headers
        run: |
          FRONTEND_URL="${{ secrets.FRONTEND_URL }}"
          BACKEND_URL="${{ secrets.VITE_BACKEND_URL }}"
          
          echo "Checking frontend security headers..."
          curl -I "$FRONTEND_URL" | grep -E "(X-Frame-Options|X-Content-Type-Options|Strict-Transport-Security|Content-Security-Policy)"
          
          echo "Checking backend security headers..."
          curl -I "$BACKEND_URL/health" | grep -E "(X-Frame-Options|X-Content-Type-Options|Strict-Transport-Security|Content-Security-Policy)"

  # Container scanning (if using Docker)
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    if: false # Enable when Docker is implemented
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  # API Security Testing
  api-security:
    name: API Security Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: ${{ secrets.VITE_BACKEND_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  # Security summary
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [codeql, dependency-scan, secret-scan, owasp-check]
    if: always()
    steps:
      - name: Create security summary
        uses: actions/github-script@v7
        with:
          script: |
            const results = {
              'CodeQL Analysis': '${{ needs.codeql.result }}',
              'Dependency Scan': '${{ needs.dependency-scan.result }}',
              'Secret Scan': '${{ needs.secret-scan.result }}',
              'OWASP Check': '${{ needs.owasp-check.result }}'
            };
            
            let hasFailures = false;
            let summary = '## Security Scan Summary\n\n';
            
            for (const [check, result] of Object.entries(results)) {
              const emoji = result === 'success' ? '✅' : '❌';
              summary += `- ${emoji} ${check}: ${result}\n`;
              if (result === 'failure') hasFailures = true;
            }
            
            if (hasFailures) {
              core.setFailed('Security scans detected issues');
            }
            
            // Post comment on PR if applicable
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: summary
              });
            }